name: Tests

on:
  pull_request:
    types: [ opened, reopened ]
    branches:
      - master
  push:
    branches:
      - master
jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ubuntu-latest]
                php: [8.1, 8.0, 7.4]
                stability: [prefer-stable]

        name: P${{ matrix.php }} - ${{ matrix.stability }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
                  coverage: xdebug2

            - name: Setup problem matchers
              run: |
                  echo "::add-matcher::${{ runner.tool_cache }}/php.json"
                  echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
            - name: Install dependencies
              run: composer update --${{ matrix.stability }} --prefer-dist --no-interaction

            - name: Execute tests
              run: |
                ./vendor/bin/phpunit --coverage-clover=coverage-report.xml --log-junit=tests-report.xml
                sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage-report.xml
                sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' tests-report.xml
              env:
                XDEBUG_MODE: coverage
            - name: Upload Test Results Coverage
              uses: actions/upload-artifact@v3
              with:
                name: code-coverage-report
                path: ./coverage-report.xml

            - name: Upload Test Results Tests
              uses: actions/upload-artifact@v3
              with:
                name: code-test-report
                path: ./tests-report.xml